// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTrvK8Plq6sw8knCZXhIck1sAkRM3yFc',
    appId: '1:524401421488:web:4d130b38ee0145c9925f75',
    messagingSenderId: '524401421488',
    projectId: 'spotify-01728',
    authDomain: 'spotify-01728.firebaseapp.com',
    storageBucket: 'spotify-01728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxItLcskf_O9Q-sxLcyVCwd-sd8t_Llk',
    appId: '1:524401421488:android:13b4506b8d810792925f75',
    messagingSenderId: '524401421488',
    projectId: 'spotify-01728',
    storageBucket: 'spotify-01728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs6lGczCGz1d9veILWdh8WypzhrxzD1U8',
    appId: '1:524401421488:ios:c50b2a83288cb261925f75',
    messagingSenderId: '524401421488',
    projectId: 'spotify-01728',
    storageBucket: 'spotify-01728.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs6lGczCGz1d9veILWdh8WypzhrxzD1U8',
    appId: '1:524401421488:ios:c50b2a83288cb261925f75',
    messagingSenderId: '524401421488',
    projectId: 'spotify-01728',
    storageBucket: 'spotify-01728.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPTrvK8Plq6sw8knCZXhIck1sAkRM3yFc',
    appId: '1:524401421488:web:d073e2ebe9c601dd925f75',
    messagingSenderId: '524401421488',
    projectId: 'spotify-01728',
    authDomain: 'spotify-01728.firebaseapp.com',
    storageBucket: 'spotify-01728.appspot.com',
  );
}
